version: '3.9'

services:
  db:
    image: postgres:bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    volumes:
      - .:/code
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db/quiz_db
    ports:
      - '8000:8000'
    depends_on:
      - db


volumes:
  postgres_data:
