"""updated created_at field

Revision ID: 5a5a524c189b
Revises: 34dbd1c61d7e
Create Date: 2023-06-08 13:02:45.162262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5a524c189b'
down_revision = '34dbd1c61d7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
